version: '3.8'
services:
  aggregator-bot:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8080:8000"
    volumes:
      - ./:/app  # This syncs your entire project folder